name: Golang CI Pipeline

on:
  workflow_call:
jobs:
  go-setup-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get GO version from go.mod
        run: |
          echo "go_version=$(grep '^go ' go.mod | awk '{print $2}')" >> $GITHUB_ENV

      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.go_version }}
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11